const express = require('express')
const multer = require('multer')
const path = require('path')
const fs = require('fs')
const joi = require('joi')
const cors = require('cors')
const mongoose = require('mongoose')
const app = express()